---
# PostgreSQL service handlers

- name: restart postgresql
  systemd:
    name: "{{ postgresql_daemon[ansible_pkg_mgr][0] }}"
    state: restarted
  become: yes

- name: reload postgresql
  systemd:
    name: "{{ postgresql_daemon[ansible_pkg_mgr][0] }}"
    state: reloaded
  become: yes