---
# playbooks/manage_postgresql.yml
- name: "Manage PostgreSQL Configurations"
  hosts: all
  gather_facts: yes
  
  roles:
    - role: postgresql_on_premise
      when: db_type == 'onprem'

    - role: postgresql_managed
      when: db_type == 'managed'

  tasks:
    - name: Placeholder task to show playbook ran
      ansible.builtin.debug:
        msg: "Finished managing PostgreSQL for project on {{ inventory_hostname }}"
