- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Check user ansible exists
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        state: present
    - name: Deploy SSH Key
      authorized_key:
        user: ansible
        key: "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"
        state: present
    - name: Add ansible user to /etc/sudoers.d/
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/ansible"
        content: |
          ansible  ALL=(ALL)  NOPASSWD: ALL
        force: true